version: '3.0'

services:
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress-42
    env_file:
      - ./.env
    networks:
      - inception-network
    volumes:
      - socket-file:/run/php
      - index-file:/var/www/wordpress

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb-42
    environment:
      - MARIADB_USER=dbrandao
      - MARIADB_PASSWORD=notsecret123
      - MARIADB_DATABASE=mary
      - DB_ROOT_PASSWORD=toor
    networks:
      - inception-network

  nginx:
    build: ./requirements/nginx
    container_name: nginx-42
    networks:
      - inception-network
    ports:
      - 4000:80
    volumes:
      - socket-file:/run/php
      - index-file:/var/www/wordpress

networks:
  inception-network:

volumes:
  socket-file:
  index-file:
  