version: '3.0'

services:
  mariadb:
    build: ./MariaDB/
    container_name: mariadb
    environment:
      - MARIADB_USER=dbrandao
      - MARIADB_PASSWORD=notsecret123
      - MARIADB_DATABASE=mary
      - DB_ROOT_PASSWORD=toor
    ports:
      - 3307:3306
