version: '3.0'

services:
  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    environment:
      - MARIADB_USER=dbrandao
      - MARIADB_PASSWORD=notsecret123
      - MARIADB_DATABASE=mary
      - DB_ROOT_PASSWORD=toor
    ports:
      - 3307:3306
    networks:
      - inception


  # nginx:
  #   build: ./requirements/nginx
  #   container_name: nginx
  #   volumes:
  #     - ./requirements/nginx/nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     - 3000:80
  #   networks:
  #     - inception


  # wordpress:
  #   build: ./requirements/wordpress
  #   container_name: wordpress
  #   ports:
  #     - 3005:80
  #   depends_on:
  #     - mariadb
  #   networks:
  #     - inception

networks:
  inception:
    name: inception